FROM node:20-alpine

WORKDIR /app

COPY --chown=node:node package*.json ./

RUN npm install && chown -R node:node /app/node_modules

COPY --chown=node:node . .

RUN chown -R node:node /app

USER node

EXPOSE 3000

ENV HOST=0.0.0.0
ENV PORT=3000

CMD ["npm", "start"]
